function observe(){var O='bootstrap',P='begin',Q='gwt.codesvr.observe=',R='gwt.codesvr=',S='observe',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='observe::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='observe.nocache.js',Ib='base',Jb='//',Kb='observeCapability',Lb='native',Mb='js',Nb='user.agent',Ob='webkit',Pb='safari',Qb='msie',Rb=10,Sb=11,Tb='ie10',Ub=9,Vb='ie9',Wb=8,Xb='ie8',Yb='gecko',Zb='gecko1_8',$b=2,_b=3,ac=4,bc='selectingPermutation',cc='observe.devmode.js',dc='D5A5C90C2C7BA182FE70271AF25074DC',ec=':1',fc=':2',gc=':3',hc=':4',ic=':',jc='.cache.js',kc='loadExternalRefs',lc='end',mc='http:',nc='file:',oc='_gwt_dummy_',pc='__gwtDevModeHook:observe',qc='Ignoring non-whitelisted Dev Mode URL: ',rc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
observe.__sendStats=r;observe.__moduleName=S;observe.__errFn=null;observe.__moduleBase=U;observe.__softPermutationId=V;observe.__computePropValue=null;observe.__getPropMap=null;observe.__installRunAsyncCode=function(){};observe.__gwtStartLoadingFragment=function(){return null};observe.__gwt_isKnownPropertyValue=function(){return false};observe.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};observe.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[observe.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
observe.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(observe.__errFn){n.onerror=function(){observe.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
observe.__startLoadingFragment=function(a){return D(a)};observe.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;observe.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return observe.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){return S in Object?Lb:Mb};i[Kb]={js:V,'native':W};j[Nb]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(Ob)!=-1}())return Pb;if(function(){return a.indexOf(Qb)!=-1&&(b>=Rb&&b<Sb)}())return Tb;if(function(){return a.indexOf(Qb)!=-1&&(b>=Ub&&b<Sb)}())return Vb;if(function(){return a.indexOf(Qb)!=-1&&(b>=Wb&&b<Sb)}())return Xb;if(function(){return a.indexOf(Yb)!=-1||b>=Sb}())return Zb;return bb};i[Nb]={gecko1_8:V,ie10:W,ie8:$b,ie9:_b,safari:ac};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};observe.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};observe.__computePropValue=k;o.__gwt_activeModules[S].bindings=observe.__getPropMap;r(O,bc);if(q()){return D(cc)}var l;try{h([Mb,Zb],dc);h([Mb,Tb],dc+ec);h([Mb,Xb],dc+fc);h([Mb,Vb],dc+gc);h([Lb,Pb],dc+hc);l=f[k(Kb)][k(Nb)];var m=l.indexOf(ic);if(m!=-1){g=parseInt(l.substring(m+W),Rb);l=l.substring(V,m)}}catch(a){}observe.__softPermutationId=g;return D(l+jc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(kc,P);r(kc,lc)}
B();observe.__moduleBase=C();t[S].moduleBase=observe.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==mc||o.location.protocol==nc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=oc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=pc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(qc+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+rc]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,lc);A(H);return true}
observe.succeeded=observe();